
CREATE TABLE [User](
	UserID INT NOT NULL IDENTITY(1,1)
	,Email NVARCHAR(255) NOT NULL UNIQUE
	,PasswordHash BINARY(32) NOT NULL
	,PasswordSalt BINARY(16) NOT NULL
	,MiB SMALLINT NOT NULL
	,Iterations SMALLINT NOT NULL
	,DegreeOfParallelism SMALLINT NOT NULL
	,LockoutExpiry DATETIME2 NOT NULL DEFAULT('2022-01-01')
	,FailedPasswordCount SMALLINT DEFAULT(0) NOT NULL
	,CONSTRAINT PK_User PRIMARY KEY(UserID)
)
