
DELIMITER //

DROP PROCEDURE IF EXISTS ins_User;
CREATE PROCEDURE ins_User(
	IN e NVARCHAR(255)
	,IN p VARCHAR(60))
BEGIN
	INSERT INTO user(Email, PasswordHash) VALUES(TRIM(e), p);
END //

DELIMITER ;