
DELIMITER //

DROP PROCEDURE IF EXISTS del_User;
CREATE PROCEDURE del_User(
	IN uID INT
)
BEGIN
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
		RESIGNAL;
	END;
	START TRANSACTION;
	DELETE FROM EnvelopeTransaction WHERE EnvelopeID IN (SELECT EnvelopeID FROM ENVELOPE WHERE UserID = uID);
	DELETE FROM Envelope WHERE UserID = uID;
	DELETE FROM User WHERE UserID = uID;
	COMMIT;
END //

DELIMITER ;