
DELIMITER //

DROP PROCEDURE IF EXISTS del_User;
CREATE PROCEDURE del_User(
	IN uID INT UNSIGNED
)
BEGIN
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
		RESIGNAL;
	END;
	START TRANSACTION;
	DELETE FROM envelopetransaction WHERE EnvelopeID IN (SELECT EnvelopeID FROM ENVELOPE WHERE UserID = uID);
	DELETE FROM ENVELOPE WHERE UserID = uID;
	DELETE FROM USER WHERE UserID = uID;
	COMMIT;
END //

DELIMITER ;