
CREATE TABLE User(
	UserID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
	,Email NVARCHAR(255) NOT NULL UNIQUE
	,PasswordHash BINARY(32) NOT NULL
	,PasswordSalt BINARY(16) NOT NULL
	,MiB TINYINT UNSIGNED NOT NULL
	,Iterations TINYINT UNSIGNED NOT NULL
	,DegreeOfParallelism TINYINT UNSIGNED NOT NULL
	,LockoutExpiry DATETIME NOT NULL DEFAULT('2022-01-01')
	,FailedPasswordCount SMALLINT UNSIGNED DEFAULT(0) NOT NULL
)