
CREATE TABLE User(
	UserID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
	,Email NVARCHAR(255) NOT NULL UNIQUE
	,PasswordHash VARCHAR(60) NOT NULL
	,LockoutExpiry DATETIME NOT NULL DEFAULT('2022-01-01')
	,FailedPasswordCount SMALLINT UNSIGNED DEFAULT(0) NOT NULL
)