CREATE TABLE Envelope(
	EnvelopeID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
	,UserID INT UNSIGNED NOT NULL
	,EnvelopeNumber SMALLINT UNSIGNED NOT NULL
	,EnvelopeName NVARCHAR(50) NOT NULL
	,CONSTRAINT FK_Envelope_UserID FOREIGN KEY (UserID) REFERENCES user(UserID)
	,CONSTRAINT AK_Envelope_UserIDNumber UNIQUE (UserID, EnvelopeNumber)
)